name: Linux CI

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'
      - README.md

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build renderer
        run: |
          cd renderer
          npm ci --legacy-peer-deps
          npm run make-index-files
          npm run build

      - name: Build main
        run: |
          cd main
          npm ci
          npm run build

      - name: Package AppImage
        run: |
          cd main
          npx electron-builder build --linux AppImage -p never
